services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test_db
    ports:
      - "5433:5432" # Пробрасываем на другой порт, чтобы не мешать основной БД